name: triary_app

packages:
  - .
  - packages/*

scripts:
  codegen:
    description: Прогнать build_runner во всех пакетах, где он есть
    run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
